name: Test Suite
on:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -e .
      - run: pytest
        env:
          PYTHONPATH: src
